[
  ./hardware/keyboard.nix
  ./hardware/linode.nix
  ./hardware/yubikey.nix
  ./overlays.nix
  ./programs/dwm.nix
  ./services/ambience.nix
  ./services/catbus-lgtv.nix
  ./services/catbus-networkpresence.nix
  ./services/catbus-snapcast.nix
  ./services/catbus-wakeonlan.nix
  ./services/dlnatoad.nix
  ./services/helix-directory-jackalope.nix
  ./services/helix-directory.nix
  ./services/helix-player.nix
  ./services/mosquitto.nix
  ./services/snapclient.nix
  ./services/ssh.nix
  ./services/upmpdcli.nix
  ./users/eth.nix
]
